# Adapted from: https://github.com/marketplace/actions/compile-arduino-sketches
# 
# To customize:
#  - Select which platforms to build and edit the matrix section below
#  - Add library dependencies as needed for this repo in the libraries section below
#
name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    strategy:
      matrix:
        include:
          - arch: msp-F5529-gcc9
            fqbn: 'energia:msp430gcc9:MSP-EXP430F5529LP'
            platform-name: 'energia:msp430gcc9'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp-F5529
            fqbn: 'energia:msp430:MSP-EXP430F5529LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp430_index.json'
          - arch: msp432
            fqbn: 'energia:msp432:MSP-EXP432P401R'
            platform-name: 'energia:msp432'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_msp432_index.json'
          - arch: tivac
            fqbn: 'energia:tivac:EK-TM4C123GXL'
            platform-name: 'energia:tivac'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/refs/heads/main/json/package_energia_minimal_tiva_index.json'

    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/arduino-compile-sketches.yml@main
    with:
      message: ${{ inputs.message }}
      copyfile: 
      fqbn: ${{ matrix.fqbn }}
      platform-name: ${{ matrix.platform-name }}
      platform-sourceurl: ${{ matrix.platform-sourceurl }}
      platform-version: latest
      libraries: |
        - source-path: ./



